packages:
  - examples/*
  - packages/*
  - legacy/*
  - apps/*

catalog:
  '@exodus/schemasafe': ^1.3.0
  '@tailwindcss/vite': ^4.1.16
  ajv: ^8.17.1
  autoprefixer: ^10.4.21
  esm-env: ^1.2.2
  globals: 16.4.0
  playwright: 1.54.1
  postcss: ^8.5.6
  svelte: ^5.43.0
  tailwindcss: ^4.1.16
  vite: ^7.1.12
  vitest: ^4.0.4
  zod: 4.1.12

catalogs:
  legacy:
    tailwindcss: ^3.4.18

onlyBuiltDependencies:
  - esbuild
  - '@tailwindcss/oxide'
