packages:
  - "packages/*"
  - "apps/*"

catalog:
  "ajv": "^8.17.1"
  "vite": "6.3.2"
  "vitest": "3.1.3"
  "svelte": "^5.28.2"
  "esm-env": "^1.2.2"
  "@sveltejs/kit": "^2.20.8"
  "@sveltejs/adapter-static": "^3.0.8"
  "@sveltejs/package": "^2.3.11"
  "@sveltejs/vite-plugin-svelte": "^5.0.3"
  "svelte-check": "^4.1.6"
  "@tsconfig/svelte": "^5.0.4"
  "@playwright/test": "^1.52.0"
  "@types/eslint": "^9.6.1"
  "autoprefixer": "^10.4.21"
  "eslint": "^9.25.1"
  "eslint-config-prettier": "^10.1.2"
  "eslint-plugin-svelte": "^3.5.1"
  "globals": "^16.0.0"
  "postcss": "^8.5.3"
  "prettier": "^3.5.3"
  "prettier-plugin-svelte": "^3.3.3"
  "tailwindcss": "^3.4.17"
  "typescript-eslint": "^8.31.1"
  "zod": "^3.24.3"
