packages:
  - examples/*
  - packages/*
  - legacy/*
  - apps/*
  - lab/*

catalog:
  '@exodus/schemasafe': ^1.3.0
  '@tailwindcss/vite': ^4.1.17
  ajv: ^8.17.1
  autoprefixer: ^10.4.22
  esm-env: ^1.2.2
  globals: 16.5.0
  playwright: 1.54.1
  postcss: ^8.5.6
  svelte: ^5.43.6
  tailwindcss: ^4.1.17
  vite: ^7.2.2
  vitest: ^4.0.9
  zod: 4.1.12
  bits-ui: 2.14.3

catalogs:
  legacy:
    tailwindcss: ^3.4.18

onlyBuiltDependencies:
  - esbuild
  - '@tailwindcss/oxide'
