packages:
  - examples/*
  - packages/*
  - legacy/*
  - apps/*
  - lab/*

catalog:
  "@exodus/schemasafe": ^1.3.0
  "@tailwindcss/vite": ^4.1.18
  "@lucide/svelte": "^0.564.0"

  "@internationalized/date": "3.11.0"
  ajv: ^8.17.1
  autoprefixer: ^10.4.24
  bits-ui: 2.15.5
  esm-env: ^1.2.2
  globals: 17.3.0
  playwright: 1.57.0
  postcss: ^8.5.6
  svelte: ^5.51.0
  tailwindcss: ^4.1.18
  vite: ^7.3.1
  vitest: ^4.0.18
  zod: 4.3.6

catalogs:
  legacy:
    tailwindcss: ^3.4.19

onlyBuiltDependencies:
  - esbuild
  - "@tailwindcss/oxide"
