packages:
  - examples/*
  - packages/*
  - apps/*

catalog:
  vite: ^7.1.2
  vitest: ^3.2.4
  ajv: 8.17.1
  svelte: ~5.38.1
  esm-env: ^1.2.2
  globals: ^16.3.0
  zod: ^4.0.17
  tailwindcss: ^4.1.11
  "@tailwindcss/vite": ^4.1.11
  "@exodus/schemasafe": ^1.3.0
  autoprefixer: ^10.4.21
  postcss: ^8.5.6

catalogs:
  legacy:
    tailwindcss: ^3.4.17
    zod: ~3.25.76
