import {
  externalValidatorPackage,
  extraPackage,
  formPackage,
  internalValidatorSubPath,
  type PrecompiledValidator,
} from "meta";

import {
  isEndsWithPrecompiled,
  POST_JSON_SCHEMA_PATH,
  withoutPrecompiledSuffix,
  type Context,
} from "./model.js";
import { transforms } from "./sv-utils.js";

export function scriptsFolder(ctx: Context) {
  const {
    options: { validatorWithSuffix },
    file,
    language,
    sv,
    ts,
  } = ctx;
  if (!isEndsWithPrecompiled(validatorWithSuffix)) {
    return;
  }

  const validator = withoutPrecompiledSuffix(validatorWithSuffix);

  const hyperjump = createScriptRenderer({
    parallel: false,
    vendorImports: `import {
  registerSchema,
  unregisterSchema,${ts("\n  type SchemaObject,")}
} from "@hyperjump/json-schema/draft-07";
import { compile, getSchema } from "@hyperjump/json-schema/experimental";
import { uneval } from "${extraPackage("devalue").name}";`,
    compileSchemaBody: ({ definePatchAndSchemas, saveModel }) => `let id = 0;
const toId = (n${ts(": number")}) => \`https://example.com/v\${n}\`;
${definePatchAndSchemas(`createId: () => toId(id++)`)}

for (const schema of schemas) {
  registerSchema(
    Object.assign(
      { $schema: "http://json-schema.org/draft-07/schema" },
      schema${ts(" as SchemaObject")}
    )
  );
}

try {
  const { ast } = await compile(await getSchema(toId(0)));
  ${saveModel({
    importStatements: `import { uneval } from "devalue"${ts(`;
import type { AST } from "@hyperjump/json-schema/experimental"`)};`,
    exportStatements: `export const ast = \${uneval(ast)}${ts(" as unknown as AST")};`,
  })};
} finally {
  for (const schema of schemas) {
    unregisterSchema(schema.$id${ts("!")});
  }
}

`,
  });

  const scripts: Record<PrecompiledValidator, (ctx: Context) => string> = {
    ajv8,
    schemasafe,
    hyperjump,
  };

  sv.file(
    `scripts/compile-validators.${language}`,
    transforms.script(({ ast, comments, js }) => {
      const code = scripts[validator](ctx);
      js.common.appendFromString(ast, {
        comments,
        code,
      });
    }),
  );

  sv.file(
    file.package,
    transforms.json(({ data, json }) => {
      json.packageScriptsUpsert(
        data,
        "sjsf:compile",
        `node scripts/compile-validators.${language}`,
      );
      json.packageScriptsUpsert(data, "prepare", "npm run sjsf:compile");
    }),
  );
}

interface ScriptOptions {
  vendorImports: string;
  compileSchemaBody: (options: {
    definePatchAndSchemas: (extra?: string) => string;
    saveModel: (
      options?: Partial<{
        importStatements: string;
        exportStatements: string;
      }>,
    ) => string;
    saveValidators: (content: string) => string;
  }) => string;
  parallel: boolean;
}

function createScriptRenderer({
  vendorImports,
  compileSchemaBody,
  parallel,
}: ScriptOptions) {
  return ({
    directory,
    ts,
    language,
  }: Context) => `import fs from "node:fs/promises";
import path from "node:path";

import { ON_ARRAY_CHANGE, ON_CHANGE, ON_INPUT } from "${formPackage.name}";
import {
  insertSubSchemaIds,
  fragmentSchema,
} from "${internalValidatorSubPath("precompile")}";

${vendorImports};

const FIELDS_VALIDATION = { ON_INPUT, ON_CHANGE, ON_ARRAY_CHANGE };
const FIELDS_VALIDATION_KEYS = Object.keys(FIELDS_VALIDATION).join(", ");
const FIELDS_VALIDATION_MODE = Object.keys(FIELDS_VALIDATION).join(" | ");
const FIELDS_VALIDATION_MODE_VALUE = Object.values(FIELDS_VALIDATION).reduce(
  (a, b) => a | b,
);
const JSON_SCHEMA_PATHS = ["${directory.lib}${POST_JSON_SCHEMA_PATH}"];
const SCRIPT_PATH = path.relative(process.cwd(), import.meta.filename);

async function compileSchema(schemaRelPath${ts(": string")}) {
  const schemaPath = path.resolve(schemaRelPath);
  const schemaDir = path.dirname(schemaPath);
  const source = await fs.readFile(schemaPath, "utf-8");
  const schema = JSON.parse(source);

  ${compileSchemaBody({
    definePatchAndSchemas: (
      extraProperties = "",
    ) => `const patch = insertSubSchemaIds(schema, {
  fieldsValidationMode: FIELDS_VALIDATION_MODE_VALUE,
  ${extraProperties}
});
const schemas = fragmentSchema(patch)`,
    saveModel: ({
      importStatements = "",
      exportStatements = "",
    } = {}) => `// It is easier to save as a TS file
// https://github.com/microsoft/TypeScript/issues/32063
await fs.writeFile(
  path.join(schemaDir, "model.generated.${language}"),
  \`// Generated by \${SCRIPT_PATH} - do not edit
${ts(`import type { Schema } from "${formPackage.name}";
import type { FromSchema } from "${extraPackage("jsonSchemaToTs").name}";
`)}import { \${FIELDS_VALIDATION_KEYS} } from "${formPackage.name}";
${importStatements}
export const fieldsValidationMode = \${FIELDS_VALIDATION_MODE};
export const schema = \${JSON.stringify(patch.schema, null, 2)}${ts(` as const satisfies Schema;
export type Post = FromSchema<typeof schema>`)};
${exportStatements}\`
  )`,
    saveValidators: (content) =>
      `await fs.writeFile(path.join(schemaDir, "validators.generated.js"), \`// @ts-nocheck\n\${${content}}\`)`,
  })}
}

async function main() {
  ${
    parallel
      ? `await Promise.all(
    JSON_SCHEMA_PATHS.map(compileSchema)
  );`
      : `for (const p of JSON_SCHEMA_PATHS) {
    await compileSchema(p)
  }`
  }
}

if (import.meta.main) {
  await main();
}
`;
}

const ajv8 = createScriptRenderer({
  parallel: true,
  vendorImports: `import { addFormComponents, DEFAULT_AJV_CONFIG } from "${externalValidatorPackage("ajv8").name}";
import Ajv from "ajv";
import standaloneCode from "ajv/dist/standalone/index.js";
import addFormats from "${extraPackage("ajvFormat").name}";
import { build } from "${extraPackage("esbuild").name}"`,
  compileSchemaBody: ({
    definePatchAndSchemas,
    saveModel,
    saveValidators,
  }) => `${definePatchAndSchemas()};
${saveModel()};

const ajv = new Ajv({
  ...DEFAULT_AJV_CONFIG,
  schemas,
  code: {
    source: true,
    esm: true,
  },
});
const modules = standaloneCode(addFormComponents(addFormats(ajv)));

// https://github.com/ajv-validator/ajv/issues/2209#issuecomment-2580172967
const { outputFiles } = await build({
  minify: true,
  bundle: true,
  write: false,
  format: "esm",
  platform: "browser",
  target: ["es2020"],
  sourcemap: false,
  stdin: {
    contents: modules,
    resolveDir: process.cwd(),
    sourcefile: "input.js",
    loader: "js",
  },
});
const bundle = outputFiles[0].text;
${saveValidators("bundle")};`,
});

const schemasafe = createScriptRenderer({
  parallel: true,
  vendorImports: `import { validator } from "@exodus/schemasafe";
import {
  DEFAULT_VALIDATOR_OPTIONS,
  FORM_FORMATS,
} from "${externalValidatorPackage("schemasafe").name}"`,
  compileSchemaBody: ({
    definePatchAndSchemas,
    saveModel,
    saveValidators,
  }) => `${definePatchAndSchemas()};
${saveModel()};
// @ts-expect-error Typings for \`multi\` version are missing
const validate = validator(schemas, {
  ...DEFAULT_VALIDATOR_OPTIONS,
  formats: FORM_FORMATS,
  schemas: new Map(schemas.map((schema) => [schema.$id, schema])),
  multi: true,
});

const validateFunctions = \`export const [\${schemas.map((s) => s.$id).join(", ")}] = \${validate.toModule()}\`;

${saveValidators("validateFunctions")};`,
});
