export {
  type ProjectOptions,
  projectOpen,
  ProjectPlatform,
  ProjectGenericExample,
  ProjectSvelteKitExample,
  ProjectValidatorSpecificExample,
  PROJECT_PLATFORMS,
  PROJECT_GENERIC_EXAMPLES,
  PROJECT_SVELTE_KIT_EXAMPLES,
  PROJECT_VALIDATOR_SPECIFIC_EXAMPLES,
  PROJECT_VALIDATOR_SPECIFIC_EXAMPLE_VALIDATORS,
  projectValidators,
  projectThemes,
  type ProjectTheme,
  type ProjectValidator,
  type ProjectExample,
} from "./project.ts";
