// auto-generated -- do not edit. Run `npm run extract-examples` to update.
export const EXAMPLES = [
  "./arktype-starter.js",
  "./async-combobox.js",
  "./decomposed-field.js",
  "./deprecated-keyword.js",
  "./draft-2020-12.js",
  "./enum-widgets.js",
  "./form-actions-dynamic-schema.js",
  "./form-actions-flex.js",
  "./form-actions-without-js.js",
  "./form-actions.js",
  "./formulas.js",
  "./label-on-left.js",
  "./layout-slots.js",
  "./markdown-description.js",
  "./multi-step-native-form.js",
  "./multi-step.js",
  "./nullable-fields.js",
  "./optional-data-controls.js",
  "./pattern-properties-validator.js",
  "./preupload-file.js",
  "./remote-enum.js",
  "./remote-functions-dynamic-schema.js",
  "./remote-functions-enhance.js",
  "./remote-functions-without-js.js",
  "./remote-functions.js",
  "./schema-transformation.js",
  "./starter.js",
  "./tabbed-layout.js",
  "./typebox-starter.js",
  "./valibot-starter.js",
  "./zod-starter.js",
] as const;

export type Example = (typeof EXAMPLES)[number];
