// auto-generated -- do not edit. Run `npm run extract-examples` to update.
export const EXAMPLES = [
  "./arktype-starter.ts",
  "./async-combobox.ts",
  "./decomposed-field.ts",
  "./deprecated-keyword.ts",
  "./draft-2020-12.ts",
  "./enum-widgets.ts",
  "./form-actions-dynamic-schema.ts",
  "./form-actions-flex.ts",
  "./form-actions-without-js.ts",
  "./form-actions.ts",
  "./formulas.ts",
  "./label-on-left.ts",
  "./layout-slots.ts",
  "./markdown-description.ts",
  "./multi-step-native-form.ts",
  "./multi-step.ts",
  "./nullable-fields.ts",
  "./optional-data-controls.ts",
  "./pattern-properties-validator.ts",
  "./preupload-file.ts",
  "./remote-enum.ts",
  "./remote-functions-dynamic-schema.ts",
  "./remote-functions-enhance.ts",
  "./remote-functions-without-js.ts",
  "./remote-functions.ts",
  "./schema-transformation.ts",
  "./starter.ts",
  "./tabbed-layout.ts",
  "./typebox-starter.ts",
  "./valibot-starter.ts",
  "./zod-starter.ts",
] as const;

export type Example = (typeof EXAMPLES)[number];
