import { parse, print } from "svelte/compiler";
import type { Schema, UiSchema } from "@sjsf/form";
import { jsonSchemaToZod } from "json-schema-to-zod";
import { jsonSchemaToValibot, type JsonSchema as ValibotJsonSchema } from "json-schema-to-valibot";
import {
  externalValidatorPackage,
  filterPackageDependencies,
  formIdBuilderSubPath,
  formMergerSubPath,
  formPackage,
  formResolverSubPath,
  formTranslationSubPath,
  iconSetPackage,
  isSchemaValidator,
  themeExtraWidgetOptionalDependencies,
  themePackage,
  toTheme,
  zod4ValidatorVersionSubPath,
  type ExtraWidgetFileNames,
  type SchemaValidator,
  type Theme,
  type ToTheme
} from "meta";
import type { PlaygroundIconSet, PlaygroundResolver, PlaygroundTheme } from "meta/playground";
import type { BuilderValidator } from "meta/builder";

import type { WidgetType } from "$lib/sjsf/theme.js";

import {
  isBaseWidget,
  WIDGET_EXTRA_FIELD,
  type ExtraWidgetType,
  EXTRA_WIDGET_IMPORTS,
  type FileFieldMode,
  fileFieldModeToFields
} from "./model.js";

export interface FormDefaultsOptions {
  widgets: Set<WidgetType>;
  resolver: PlaygroundResolver;
  theme: PlaygroundTheme;
  icons: PlaygroundIconSet;
  validator: BuilderValidator;
  fileFieldMode: FileFieldMode;
}

function camelToKebabCase(str: string): string {
  return str.replace(/([A-Z])/g, "-$1").toLowerCase();
}

export function join(...args: (string | false)[]) {
  return args.filter(Boolean).join("\n");
}

function join2(...args: (string | false)[]) {
  return args.filter(Boolean).join("\n\n");
}

export function buildFormDefaults({
  widgets,
  icons,
  resolver,
  theme,
  validator,
  fileFieldMode
}: FormDefaultsOptions): string {
  const extraFields = new Set<string>();
  const extraWidgetTypes: ExtraWidgetType[] = [];
  for (const w of widgets) {
    if (!isBaseWidget(w)) {
      extraWidgetTypes.push(w);
    }
    const fields = fileFieldModeToFields(fileFieldMode);
    const widgetExtraField = WIDGET_EXTRA_FIELD[w];
    if (widgetExtraField !== undefined) {
      fields.push(widgetExtraField);
    }
    for (const f of fields) {
      extraFields.add(f);
    }
  }

  const iconsExport =
    icons === "none" ? false : `export { icons } from "${iconSetPackage(icons).name}";`;

  const themePkg = themePackage(toTheme(theme));

  return join2(
    join(
      `export { resolver } from "${formResolverSubPath(resolver)}";`,
      ...Array.from(extraFields).map(
        (f) => `import "@sjsf/form/fields/extra/${camelToKebabCase(f)}-include";`
      )
    ),
    join(
      `export { theme } from "${themePkg.name}";`,
      ...extraWidgetTypes.map(
        (w) => `import "${themePkg.name}/extra-widgets/${EXTRA_WIDGET_IMPORTS[w]}-include";`
      )
    ),
    iconsExport,
    `export { translation } from "${formTranslationSubPath("en")}";`,
    `export { createFormIdBuilder as idBuilder } from "${formIdBuilderSubPath("modern")}";`,
    `export { createFormMerger as merger } from "${formMergerSubPath("modern")}";`,
    !(validator in VALIDATOR_ADAPTERS) &&
      `export { createFormValidator as validator } from "${externalValidatorPackage(validator).name}";`
  );
}

export interface FormDotSvelteOptions {
  theme: PlaygroundTheme;
  schema: Schema;
  validator: BuilderValidator;
  uiSchema: UiSchema | undefined;
  html5Validation: boolean;
}

const VALIDATOR_ADAPTERS: Record<BuilderValidator & SchemaValidator, string> = {
  zod4: `import { adapt } from "${zod4ValidatorVersionSubPath("classic")}";\nimport { z } from "zod";`,
  valibot: `import { adapt } from "${externalValidatorPackage("valibot").name}";\nimport * as v from "valibot";`
};

function toLines(str: string) {
  return str.split("\n").join("\n  ");
}

function jsonToLines(data: Schema | UiSchema) {
  return toLines(JSON.stringify(data, null, 2));
}

function defaultSchemaFactory(schema: Schema) {
  return `const schema = ${jsonToLines(schema)} as const satisfies Schema`;
}

const SCHEMA_FACTORIES: Record<BuilderValidator, (schema: Schema) => string> = {
  ajv8: defaultSchemaFactory,
  schemasafe: defaultSchemaFactory,
  cfworker: defaultSchemaFactory,
  ata: defaultSchemaFactory,
  zod4: (schema) => `
		// This code was generated by the 'json-schema-to-zod' library and
		// may not fully match the original schema
		${jsonSchemaToZod(schema, {
      noImport: true,
      name: "schema"
    })}`,
  valibot: (schema) => `
		// This code was generated by the 'json-schema-to-valibot' library and
		// may not fully match the original schema
		${jsonSchemaToValibot(schema as ValibotJsonSchema, {
      module: "none"
    })}`
};

export function buildFormDotSvelte({
  theme,
  schema,
  uiSchema = {},
  html5Validation,
  validator
}: FormDotSvelteOptions): string {
  const isShadcn = theme === "shadcn4";
  const isSvar = theme === "svar";
  const validatorAdapter = isSchemaValidator(validator) ? VALIDATOR_ADAPTERS[validator] : false;
  const code = join(
    `<script lang="ts">
  import { createForm, BasicForm, type Schema, type UiSchemaRoot } from "${formPackage.name}";`,
    validatorAdapter && `  ${toLines(validatorAdapter)}`,
    isShadcn &&
      `  import { setThemeContext } from "${themePackage("shadcn4").name}";
  import * as components from "${themePackage("shadcn4").name}/new-york";`,
    isSvar && `  import { Willow } from "@svar-ui/svelte-core";`,
    `
  import * as defaults from "$lib/form/defaults.js";

  ${SCHEMA_FACTORIES[validator](schema)};

  const uiSchema: UiSchemaRoot = ${jsonToLines(uiSchema)};

  const form = createForm({
    ...defaults,
    ${validatorAdapter ? "...adapt(schema)," : "schema,"}
    uiSchema,
    onSubmit: console.log
  })`,
    isShadcn &&
      `
  setThemeContext({ components })`,
    `</script>`,
    isSvar && `<Willow>`,
    `<BasicForm {form}${html5Validation ? "" : " novalidate"} />`,
    isSvar && `</Willow>`
  );
  return validatorAdapter
    ? print(parse(code, { filename: "form.svelte", modern: true })).code
    : code;
}

export interface InstallShOptions<T extends PlaygroundTheme> {
  theme: T;
  validator: BuilderValidator;
  icons: PlaygroundIconSet;
  widgets: Set<ExtraWidgetFileNames[ToTheme<T>]>;
}

function* themeOptionalDeps<T extends Theme>(theme: T, widgets: Iterable<ExtraWidgetFileNames[T]>) {
  for (const w of widgets) {
    yield* themeExtraWidgetOptionalDependencies(theme, w);
  }
}

export function buildInstallSh<T extends PlaygroundTheme>({
  theme,
  validator,
  icons,
  widgets
}: InstallShOptions<T>) {
  const t = toTheme(theme);
  const themePkg = themePackage(t);
  const deps = [
    ...filterPackageDependencies(externalValidatorPackage(validator).dependencies, false),
    ...filterPackageDependencies(themePkg.dependencies, Array.from(themeOptionalDeps(t, widgets)))
  ];

  let cmd = `npm i ${formPackage.name} ${themePkg.name} ${externalValidatorPackage(validator).name}`;
  if (icons !== "none") {
    const pkg = iconSetPackage(icons);
    cmd += ` ${pkg.name}`;
    deps.push(...filterPackageDependencies(pkg.dependencies, false));
  }
  const peerSet = new Set(deps.map((d) => d.name));
  peerSet.delete("svelte");
  peerSet.delete(formPackage.name);
  const peer = Array.from(peerSet);
  return join(peer.length > 0 && `# peer deps: ${peer.join(" ")}`, cmd);
}
