import { restoreValidator } from "@hyperjump/json-schema/draft-07";

export const validators = {
  "https://example.com/v1": restoreValidator("{\"ast\":{\"metaData\":{\"https://example.com/v1\":{\"dynamicAnchors\":{}}},\"plugins\":[],\"https://example.com/v1#\":[[\"https://json-schema.org/keyword/type\",\"https://example.com/v1#/type\",\"integer\"],[\"https://json-schema.org/keyword/minimum\",\"https://example.com/v1#/minimum\",1]]},\"schemaUri\":\"https://example.com/v1#\"}"),
  "https://example.com/v2": restoreValidator("{\"ast\":{\"metaData\":{\"https://example.com/v2\":{\"dynamicAnchors\":{}}},\"plugins\":[],\"https://example.com/v2#\":[[\"https://json-schema.org/keyword/type\",\"https://example.com/v2#/type\",\"string\"],[\"https://json-schema.org/keyword/draft-07/format\",\"https://example.com/v2#/format\",\"email\"]]},\"schemaUri\":\"https://example.com/v2#\"}"),
  "https://example.com/v3": restoreValidator("{\"ast\":{\"metaData\":{\"https://example.com/v3\":{\"dynamicAnchors\":{}}},\"plugins\":[],\"https://example.com/v3#\":[[\"https://json-schema.org/keyword/type\",\"https://example.com/v3#/type\",\"integer\"],[\"https://json-schema.org/keyword/minimum\",\"https://example.com/v3#/minimum\",21],[\"https://json-schema.org/keyword/maximum\",\"https://example.com/v3#/maximum\",100]]},\"schemaUri\":\"https://example.com/v3#\"}"),
  "https://example.com/v5": restoreValidator("{\"ast\":{\"metaData\":{\"https://example.com/v5\":{\"dynamicAnchors\":{}}},\"plugins\":[],\"https://example.com/v5#\":[[\"https://json-schema.org/keyword/type\",\"https://example.com/v5#/type\",\"string\"],[\"https://json-schema.org/keyword/enum\",\"https://example.com/v5#/enum\",[\"\\\"admin\\\"\",\"\\\"editor\\\"\",\"\\\"viewer\\\"\"]]]},\"schemaUri\":\"https://example.com/v5#\"}"),
  "https://example.com/v4": restoreValidator("{\"ast\":{\"metaData\":{\"https://example.com/v4\":{\"dynamicAnchors\":{}},\"https://example.com/v5\":{\"dynamicAnchors\":{}}},\"plugins\":[],\"https://example.com/v4#\":[[\"https://json-schema.org/keyword/type\",\"https://example.com/v4#/type\",\"array\"],[\"https://json-schema.org/keyword/draft-04/items\",\"https://example.com/v4#/items\",\"https://example.com/v5#\"],[\"https://json-schema.org/keyword/uniqueItems\",\"https://example.com/v4#/uniqueItems\",true],[\"https://json-schema.org/keyword/minItems\",\"https://example.com/v4#/minItems\",1]],\"https://example.com/v5#\":[[\"https://json-schema.org/keyword/type\",\"https://example.com/v5#/type\",\"string\"],[\"https://json-schema.org/keyword/enum\",\"https://example.com/v5#/enum\",[\"\\\"admin\\\"\",\"\\\"editor\\\"\",\"\\\"viewer\\\"\"]]]},\"schemaUri\":\"https://example.com/v4#\"}"),
  "https://example.com/v0": restoreValidator("{\"ast\":{\"metaData\":{\"https://example.com/v0\":{\"dynamicAnchors\":{}},\"https://example.com/v1\":{\"dynamicAnchors\":{}},\"https://example.com/v2\":{\"dynamicAnchors\":{}},\"https://example.com/v3\":{\"dynamicAnchors\":{}},\"https://example.com/v4\":{\"dynamicAnchors\":{}},\"https://example.com/v5\":{\"dynamicAnchors\":{}}},\"plugins\":[],\"https://example.com/v0#\":[[\"https://json-schema.org/keyword/title\",\"https://example.com/v0#/title\",\"User\"],[\"https://json-schema.org/keyword/type\",\"https://example.com/v0#/type\",\"object\"],[\"https://json-schema.org/keyword/required\",\"https://example.com/v0#/required\",[\"id\",\"email\",\"age\",\"roles\"]],[\"https://json-schema.org/keyword/properties\",\"https://example.com/v0#/properties\",{\"id\":\"https://example.com/v1#\",\"email\":\"https://example.com/v2#\",\"age\":\"https://example.com/v3#\",\"roles\":\"https://example.com/v4#\"}],[\"https://json-schema.org/keyword/additionalProperties\",\"https://example.com/v0#/additionalProperties\",[{\"a6d8f3e1-9b2c-4f7a-8d5b-1c2e3f4a5b6c\":{\"source\":\"^id$|^email$|^age$|^roles$\",\"flags\":\"u\"}},\"https://example.com/v0#/additionalProperties\"]]],\"https://example.com/v1#\":[[\"https://json-schema.org/keyword/type\",\"https://example.com/v1#/type\",\"integer\"],[\"https://json-schema.org/keyword/minimum\",\"https://example.com/v1#/minimum\",1]],\"https://example.com/v2#\":[[\"https://json-schema.org/keyword/type\",\"https://example.com/v2#/type\",\"string\"],[\"https://json-schema.org/keyword/draft-07/format\",\"https://example.com/v2#/format\",\"email\"]],\"https://example.com/v3#\":[[\"https://json-schema.org/keyword/type\",\"https://example.com/v3#/type\",\"integer\"],[\"https://json-schema.org/keyword/minimum\",\"https://example.com/v3#/minimum\",21],[\"https://json-schema.org/keyword/maximum\",\"https://example.com/v3#/maximum\",100]],\"https://example.com/v4#\":[[\"https://json-schema.org/keyword/type\",\"https://example.com/v4#/type\",\"array\"],[\"https://json-schema.org/keyword/draft-04/items\",\"https://example.com/v4#/items\",\"https://example.com/v5#\"],[\"https://json-schema.org/keyword/uniqueItems\",\"https://example.com/v4#/uniqueItems\",true],[\"https://json-schema.org/keyword/minItems\",\"https://example.com/v4#/minItems\",1]],\"https://example.com/v5#\":[[\"https://json-schema.org/keyword/type\",\"https://example.com/v5#/type\",\"string\"],[\"https://json-schema.org/keyword/enum\",\"https://example.com/v5#/enum\",[\"\\\"admin\\\"\",\"\\\"editor\\\"\",\"\\\"viewer\\\"\"]]],\"https://example.com/v0#/additionalProperties\":false},\"schemaUri\":\"https://example.com/v0#\"}"),
};
