flowchart TD
  subgraph Options["Options (createForm)"]
    schema["schema"]
    uiSchema["uiSchema"]
    uiOptionsRegistry["uiOptionsRegistry"]
    initialValue["initialValue"]
    value["value (Bind)"]
    initialErrors["initialErrors"]
    disabled["disabled"]
    fieldsValidationMode["fieldsValidationMode"]
  end

  subgraph Internal["Internal"]
    validator["validator"]
    merger["merger"]
  end

  subgraph InternalState["Internal State"]
    pathsTrieRef["pathsTrieRef"]
    fieldsStateMap["fieldsStateMap"]
    errors["errors (FormErrors)"]
  end

  subgraph FormState["FormState"]
    formValue["value"]
    formIsSubmitted["isSubmitted"]
    formIsChanged["isChanged"]
    submission["submission"]
    fieldsValidation["fieldsValidation"]
  end

  subgraph Queries["Queries"]
    getValueSnapshot["getValueSnapshot"]
    getFieldErrors["getFieldErrors"]
    hasErrors["hasErrors"]
    getErrors["getErrors"]
    validate["validate"]
    getComponent["getComponent"]
    getFieldComponent["getFieldComponent"]
    retrieveSchema["retrieveSchema"]
    isDisabled["isDisabled"]
    hasFieldStateByPath["hasFieldStateByPath"]
  end

  subgraph Commands["Commands"]
    updateErrors["updateErrors"]
    updateFieldErrors["updateFieldErrors"]
    setValue["setValue"]
    validateField["validateField"]
    setFieldStateByPath["setFieldStateByPath"]
  end

  schema --> validator
  uiSchema --> validator
  uiOptionsRegistry --> validator
  validator --> merger
  schema --> merger
  uiSchema --> merger

  schema --> pathsTrieRef

  merger --> formValue
  schema --> formValue
  value --> formValue
  initialValue --> formValue

  pathsTrieRef --> formIsSubmitted
  pathsTrieRef --> formIsChanged
  fieldsStateMap --> formIsSubmitted
  fieldsStateMap --> formIsChanged

  validator --> submission
  validator --> fieldsValidation

  initialErrors --> errors

  formValue -.-> getValueSnapshot
  errors -.-> getFieldErrors
  errors -.-> hasErrors
  errors -.-> getErrors
  formValue -.-> validate
  FormState -.-> getComponent
  FormState -.-> getFieldComponent
  FormState -.-> retrieveSchema
  FormState -.-> isDisabled
  fieldsStateMap -.-> hasFieldStateByPath

  errors -.-> updateErrors
  errors -.-> updateFieldErrors
  formValue -.-> setValue
  fieldsValidation -.-> validateField
  fieldsStateMap -.-> setFieldStateByPath
