export const WIDGETS = {
  basic: {
    widgets: {
      checkbox: "checkboxWidget",
      number: "numberWidget",
      select: "selectWidget",
      text: "textWidget",
    },
    extraWidgets: {
      checkboxes: "checkboxesWidget",
      "date-picker": "datePickerWidget",
      file: "fileWidget",
      "multi-select": "multiSelectWidget",
      radio: "radioWidget",
      range: "rangeWidget",
      textarea: "textareaWidget",
    },
    optionalDeps: {},
  },
  daisyui5: {
    widgets: {
      checkbox: "checkboxWidget",
      number: "numberWidget",
      select: "selectWidget",
      text: "textWidget",
    },
    extraWidgets: {
      "cally-date-picker": "daisyui5CallyDatePickerWidget",
      checkboxes: "checkboxesWidget",
      "date-picker": "datePickerWidget",
      file: "fileWidget",
      "filter-radio-buttons": "daisyui5FilterRadioButtonsWidget",
      "multi-select": "multiSelectWidget",
      "radio-buttons": "radioButtonsWidget",
      radio: "radioWidget",
      range: "rangeWidget",
      rating: "ratingWidget",
      switch: "switchWidget",
      textarea: "textareaWidget",
    },
    optionalDeps: {
      cally: ["cally-date-picker"],
      pikaday: ["date-picker"],
    },
  },
  flowbite3: {
    widgets: {
      checkbox: "checkboxWidget",
      number: "numberWidget",
      select: "selectWidget",
      text: "textWidget",
    },
    extraWidgets: {
      checkboxes: "checkboxesWidget",
      "date-picker": "datePickerWidget",
      "date-range-picker": "dateRangePickerWidget",
      file: "fileWidget",
      "multi-select": "multiSelectWidget",
      "radio-buttons": "radioButtonsWidget",
      radio: "radioWidget",
      range: "rangeWidget",
      switch: "switchWidget",
      tags: "tagsWidget",
      textarea: "textareaWidget",
      "toggle-radio-buttons": "flowbite3ToggleRadioButtonsWidget",
    },
    optionalDeps: {},
  },
  shadcn4: {
    widgets: {
      checkbox: "checkboxWidget",
      number: "numberWidget",
      select: "selectWidget",
      text: "textWidget",
    },
    extraWidgets: {
      checkboxes: "checkboxesWidget",
      combobox: "comboboxWidget",
      "date-picker": "datePickerWidget",
      "date-range-picker": "dateRangePickerWidget",
      file: "fileWidget",
      "multi-select": "multiSelectWidget",
      "radio-buttons": "radioButtonsWidget",
      radio: "radioWidget",
      "range-slider": "rangeSliderWidget",
      range: "rangeWidget",
      switch: "switchWidget",
      textarea: "textareaWidget",
    },
    optionalDeps: {
      "@internationalized/date": ["date-picker", "date-range-picker"],
    },
  },
  skeleton4: {
    widgets: {
      checkbox: "checkboxWidget",
      number: "numberWidget",
      select: "selectWidget",
      text: "textWidget",
    },
    extraWidgets: {
      checkboxes: "checkboxesWidget",
      combobox: "comboboxWidget",
      "date-picker": "datePickerWidget",
      "date-range-picker": "dateRangePickerWidget",
      "file-upload": "skeleton4FileUploadWidget",
      file: "fileWidget",
      "multi-select": "multiSelectWidget",
      "radio-buttons": "radioButtonsWidget",
      radio: "radioWidget",
      "range-slider": "rangeSliderWidget",
      range: "rangeWidget",
      rating: "ratingWidget",
      slider: "skeleton4SliderWidget",
      switch: "switchWidget",
      tags: "tagsWidget",
      textarea: "textareaWidget",
    },
    optionalDeps: {
      "@skeletonlabs/skeleton-svelte": [
        "combobox",
        "date-picker",
        "date-range-picker",
        "file-upload",
        "radio-buttons",
        "range-slider",
        "rating",
        "slider",
        "switch",
        "tags",
      ],
    },
  },
  beercss: {
    widgets: {
      checkbox: "checkboxWidget",
      number: "numberWidget",
      select: "selectWidget",
      text: "textWidget",
    },
    extraWidgets: {
      checkboxes: "checkboxesWidget",
      "date-picker": "datePickerWidget",
      file: "fileWidget",
      radio: "radioWidget",
      range: "rangeWidget",
      switch: "switchWidget",
      textarea: "textareaWidget",
    },
    optionalDeps: {},
  },
  "shadcn-extras": {
    widgets: {},
    extraWidgets: {
      "file-drop-zone": "shadcnExtrasFileDropZoneWidget",
      "ip-v4-address-input": "shadcnExtrasIPv4AddressInputWidget",
      "nlp-date-input": "shadcnExtrasNLPDateInputWidget",
      password: "shadcnExtrasPasswordWidget",
      "phone-input": "shadcnExtrasPhoneInputWidget",
      "star-rating": "shadcnExtrasStarRatingWidget",
      "tags-input": "shadcnExtrasTagsInputWidget",
    },
    optionalDeps: {
      "@lucide/svelte": ["file-drop-zone"],
    },
  },
  svar: {
    widgets: {
      checkbox: "checkboxWidget",
      number: "numberWidget",
      select: "selectWidget",
      text: "textWidget",
    },
    extraWidgets: {
      checkboxes: "checkboxesWidget",
      "color-picker": "svarColorPickerWidget",
      "color-select": "svarColorSelectWidget",
      combobox: "comboboxWidget",
      "date-picker": "datePickerWidget",
      "date-range-picker": "dateRangePickerWidget",
      "multi-select": "multiSelectWidget",
      "radio-buttons": "radioButtonsWidget",
      radio: "radioWidget",
      range: "rangeWidget",
      switch: "switchWidget",
      textarea: "textareaWidget",
    },
    optionalDeps: {},
  },
  daisyui: {
    widgets: {
      checkbox: "checkboxWidget",
      number: "numberWidget",
      select: "selectWidget",
      text: "textWidget",
    },
    extraWidgets: {
      checkboxes: "checkboxesWidget",
      "date-picker": "datePickerWidget",
      file: "fileWidget",
      "multi-select": "multiSelectWidget",
      "radio-buttons": "radioWidget",
      radio: "radioWidget",
      range: "rangeWidget",
      switch: "switchWidget",
      textarea: "textareaWidget",
    },
    optionalDeps: {},
  },
  flowbite: {
    widgets: {
      checkbox: "checkboxWidget",
      number: "numberWidget",
      select: "selectWidget",
      text: "textWidget",
    },
    extraWidgets: {
      checkboxes: "checkboxesWidget",
      "date-picker": "datePickerWidget",
      file: "fileWidget",
      "multi-select": "multiSelectWidget",
      radio: "radioWidget",
      range: "rangeWidget",
      switch: "switchWidget",
      textarea: "textareaWidget",
    },
    optionalDeps: {},
  },
  shadcn: {
    widgets: {
      checkbox: "checkboxWidget",
      number: "numberWidget",
      select: "selectWidget",
      text: "textWidget",
    },
    extraWidgets: {
      checkboxes: "checkboxesWidget",
      combobox: "selectWidget",
      "date-picker": "datePickerWidget",
      file: "fileWidget",
      "multi-select": "multiSelectWidget",
      "radio-buttons": "radioButtonsWidget",
      radio: "radioWidget",
      range: "rangeWidget",
      switch: "switchWidget",
      textarea: "textareaWidget",
    },
    optionalDeps: {
      "@internationalized/date": ["date-picker"],
    },
  },
  skeleton3: {
    widgets: {
      checkbox: "checkboxWidget",
      number: "numberWidget",
      select: "selectWidget",
      text: "textWidget",
    },
    extraWidgets: {
      checkboxes: "checkboxesWidget",
      combobox: "comboboxWidget",
      "date-picker": "datePickerWidget",
      "file-upload": "skeleton3FileUploadWidget",
      file: "fileWidget",
      "multi-select": "multiSelectWidget",
      "radio-buttons": "radioButtonsWidget",
      radio: "radioWidget",
      range: "rangeWidget",
      rating: "ratingWidget",
      slider: "skeleton3SliderWidget",
      switch: "switchWidget",
      tags: "tagsWidget",
      textarea: "textareaWidget",
    },
    optionalDeps: {
      "@skeletonlabs/skeleton-svelte": [
        "combobox",
        "file-upload",
        "radio-buttons",
        "rating",
        "slider",
        "switch",
        "tags",
      ],
    },
  },
} as const;
